### ISSUE TITLE
一些疑问。

### ISSUE THREAD

**Issue by vihuela** [zzyandroid0425/EXP#1]
同学你这个如果添加一个接口，要集成okHttp的抽象类，然后还要生成dao，还要写response转换bean的代码。。。。如果说接口归于一处，然后View直接调用传入转换的bean，直接在View的eventBus回调处接收Bean，中间的转换、入库、连接都不用一个新上手的人写该多好。。
      另外，项目搞个可以运行的啊

**Comment by zzyandroid0425** [comment]
项目的确有个小bug，我的失误，已经改好了，的确要像你说的那样，很好的建议，谢谢！

**Comment by JamesLebron** [comment]
同学你好.项目中遇到一个问题.需要让APP常驻定位,向服务器提交定位数据.可否一起交流一下相关的问题.我的QQ 是564757717

**Comment by chenyang1900** [comment]
期待你能够给出个例子，给个简单接口文档，那会非常更加容易读你的项目

**Comment by lamyuqing** [comment]
请教下，楼主这个greendao的封装DataBaseManager，然后还要为每个实体类专门封装一层manager得到dao，相对比我直接封装拿到所有的自动生成的dao文件对象，在除了返回值的是否成功，其他上还有什么优势吗，感觉是不是多此一举？刚接触 有点不明白 希望解答

**Comment by zzyandroid0425** [comment]
http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2015/1111/3678.html 麻烦你看看这个博客
