### ISSUE TITLE
关于关联表的问题

### ISSUE THREAD

**Issue by Lesences** [zzyandroid0425/EXP#2]
你好，
刚接触greenDao几天，我在使用greenDao的过程中，发现我删除关联表的时候，所对应的关联数据并没有被删除：

    Entity mRoom = schema.addEntity("Room");
    mRoom.addLongProperty("roomId").unique().primaryKey();
    mRoom.addStringProperty("name");

    Entity mMode = schema.addEntity("Mode");
    mRoom.addLongProperty("modeId").unique().primaryKey();
    mRoom.addStringProperty("name");

    Property mProperty = mMode.addLongProperty("relationId").getProperty();
    mMode.addToOne(mRoom, mProperty);
    mRoom.addToMany(mMode, mProperty).setName("modeList");

当我执行 roomDao.delete(myRoom); 或者roomDao.deleteAll();表Mode中相对应的数据并没有删除，，，求指点！

**Comment by zzyandroid0425** [comment]
你好：
下面是源码
    public void deleteAll() {
        // String sql = SqlUtils.createSqlDelete(config.tablename, null);
        // db.execSQL(sql);

        db.execSQL("DELETE FROM '" + config.tablename + "'");
        if (identityScope != null) {
            identityScope.clear();
        }
    }

你执行roomDao.deleteAll();其实只是删除了当前表的所有内容，和缓存中的内容。并没有关联表的删除操作，我使用过程中目前是自己删除，或者你可以重写改方法。
