### ISSUE TITLE
工程无法运行

### ISSUE THREAD

**Issue by Batows** [zzyandroid0425/EXP#3]
工程运行时，直接报错
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'E:\work_tool\tool_jdk\jdk8\bin\java.exe'' finished with non-zero exit value 1

**Comment by zzyandroid0425** [comment]
选jdk1.7吧
