### ISSUE TITLE
工程无法运行

### ISSUE THREAD

**Issue by Immortelle0411** [zzyandroid0425/EXP#4]
EXP-master\data\src\main\java\cn\org\cfpamf\data\okHttp\BaiduTestOkHttp.java
Error:(16, 35) 错误: 找不到符号
符号:   类 DatabaseManager
位置: 程序包 cn.org.cfpamf.data.database
Error:(68, 31) 错误: 无法将类 BaiduDbManager中的构造器 BaiduDbManager应用到给定类型;
需要: 没有参数
找到: Context
原因: 实际参数列表和形式参数列表长度不同
----------------------------------------------------------------
以上为AndroidStudio控制台报错的语句

**Comment by zzyandroid0425** [comment]
麻烦重新下载下，已经发现问题解决了，谢谢

**Comment by Immortelle0411** [comment]
谢谢
